export const ARENA_JOURNEY_VERSION = 2;
type JourneyStep = { id: string; title: string; text: string; hint: string; href: string; target: string; action: string; highlights?: readonly string[] };
export const ARENA_JOURNEY_STEPS: readonly JourneyStep[] = [
  { id: "welcome", title: "Du Carnet au Placard", text: "Découvre ton Carnet, tes cartes et la boutique. Je te montre comment équiper ton atelier, améliorer ta récolte puis vendre tes lots. Quatre minutes, à ton rythme.", hint: "Tu peux passer le parcours et le relancer avec le bouton Guide. Aucun achat n’est nécessaire pour suivre la visite.", href: "/arene", target: "", action: "Découvrir mon Carnet" },
  { id: "notebook", title: "1. Ouvre ton Carnet", text: "Ouvre le livre, puis repère les fleurs que tu as goûtées. Complète leur dégustation pour suivre tes découvertes et avancer dans les objectifs du Carnet.", hint: "Les avis validés et certains objectifs peuvent débloquer des récompenses. Aucune fleur débloquée ? Poursuis la visite ; note uniquement ce que tu as réellement goûté.", href: "/arene/carnet/regular", target: "[data-arena-tour='notebook']", action: "Retrouver mes cartes" },
  { id: "cards", title: "2. Découvre tes cartes", text: "Dans ta collection La Botte, retrouve les cartes possédées et celles qui manquent. Ouvre une carte pour lire son effet avant de composer ton deck.", hint: "Le Buddie choisit ta variété et donne de l’XP selon sa rareté. Les cartes La Botte t’aident à résoudre les incidents de culture.", href: "/arene/placard", target: "[data-arena-tour='collection']", action: "Visiter la boutique" },
  { id: "shop", title: "3. Fais le tour de La Botte", text: "Au comptoir, la caisse sert à acheter des packs avec tes points. Les boîtes contiennent les packs à ouvrir et les récompenses disponibles.", highlights: ["Points : pour les packs de cartes.", "Euros du jeu : pour le matériel du Placard.", "Le livre à la feuille de cannabis ouvre le rayon matériel."], hint: "Les missions peuvent aussi rapporter des packs. Tu peux continuer sans acheter ni ouvrir de pack.", href: "/arene/placard?view=shop&guide=1", target: "[data-arena-tour='equipment-book']", action: "Comparer le matériel" },
  { id: "equipment", title: "4. Améliore ta récolte", text: "Ouvre la fiche d’un équipement pour comparer ses bonus avec ton installation. Un meilleur atelier peut produire davantage et atteindre une meilleure qualité.", highlights: ["Tentes : augmentent la quantité potentielle.", "LED : améliorent le rendement et la qualité maximale.", "Extraction et climat : améliorent la régularité ; certains modèles augmentent aussi la qualité maximale."], hint: "Une qualité maximale plus haute n’est pas une note garantie : tes choix et les incidents comptent toujours. Lis aussi les prérequis et les contreparties.", href: "/arene/placard?view=shop&catalog=equipment&guide=1", target: "#equipment-catalog-title", action: "Comprendre l’installation" },
  { id: "installation", title: "5. Aménage ton entrepôt", text: "Clique sur la box ou un emplacement du décor pour installer le matériel acheté. Une seule pièce peut être active par emplacement. Les bonus sont résumés sous l’atelier.", highlights: ["La pièce séchoir renforce la qualité et la régularité des fleurs.", "Les niveaux supérieurs améliorent le matériel, mais augmentent ses charges.", "Les nouvelles installations s’appliquent aux prochaines cultures."], hint: "Garde des euros pour les charges. Commence avec le matériel fourni, puis investis grâce aux ventes. Aucun achat n’est nécessaire pour cette visite.", href: "/arene/placard?view=workshop", target: "[data-arena-tour='warehouse']", action: "Préparer ma culture" },
  { id: "culture", title: "6. Prépare ton Placard", text: "Choisis ton Buddie et tes cartes La Botte. Le sol vivant est inclus. Lance les dés, lis les incidents et joue le soutien adapté pour protéger la qualité et la quantité de ta récolte.", hint: "Vérifie ton équipement et tes charges avant de lancer une culture. Une carte La Botte n’est consommée que lorsque tu la joues. Tu peux poursuivre la visite sans démarrer de partie.", href: "/arene/placard?view=game", target: "[data-arena-tour='culture']", action: "Rencontrer le jury" },
  { id: "jury", title: "7. Présente ta fleur au jury", text: "Après la culture, engage une fleur disponible dans Fleur vs Fleur. Tu choisis ta fleur ; le duel avec une autre fleur donne le verdict et la note du lot.", hint: "Pas d’adversaire ? La fleur reste en attente. Après le duel, elle ne peut plus être engagée et son lot rejoint le marché. La visite ne lance aucun duel.", href: "/arene/placard?view=arena", target: "[data-placard-view='arena'] nav p", action: "Découvrir la vente" },
  { id: "market", title: "8. Vends au bon endroit", text: "Au marché, choisis un lot et sa transformation, puis compare les circuits de vente. Les machines installées déterminent les transformations accessibles. Regarde la qualité, le prix proposé et les quantités reprises.", highlights: ["En ligne : meilleure marge, mais ventes liées à la réputation et aux clients. Ordinateur et abonnement nécessaires.", "CBD shops : prix plus bas et volumes plus importants ; la qualité fidélise tes partenaires.", "Grossistes : prix les plus bas, débouché moins exigeant sur la qualité."], hint: "Une mauvaise qualité peut faire perdre des clients. Les ventes financent tes prochains équipements ; garde une réserve pour les charges.", href: "/arene/placard?view=market", target: "[data-placard-view='market'] nav p", action: "Choisir mon premier défi" },
  { id: "missions", title: "9. Choisis ton premier défi", text: "Produire une belle fleur, gagner des clients ou développer tes boutiques partenaires : les missions te donnent des objectifs concrets pour gagner des packs La Botte.", hint: "Ta boucle de jeu : goûter et noter, préparer tes cartes, cultiver, passer devant le jury, vendre puis améliorer ton atelier. Progresse à ton rythme !", href: "/arene/placard?view=missions", target: "[data-arena-tour='missions']", action: "Terminer · à moi de jouer" },
];
export const ARENA_JOURNEY_STEP_COUNT = ARENA_JOURNEY_STEPS.length - 1;
export type ArenaJourneyProgress = { step: number; status: "new" | "active" | "completed" | "skipped" };
export type ArenaJourneyAction = "start" | "next" | "previous" | "skip" | "restart";
export const NEW_ARENA_JOURNEY: ArenaJourneyProgress = { step: 0, status: "new" };
export function isArenaJourneyAction(value: unknown): value is ArenaJourneyAction {
  return typeof value === "string" && ["start", "next", "previous", "skip", "restart"].includes(value);
}
export function parseArenaJourneyProgress(value: unknown): ArenaJourneyProgress | null {
  if (!value || typeof value !== "object") return null;
  const row = value as Record<string, unknown>;
  return Number.isInteger(row.step) && Number(row.step) >= 0 && Number(row.step) < ARENA_JOURNEY_STEPS.length
    && typeof row.status === "string" && ["new", "active", "completed", "skipped"].includes(row.status)
    ? {step:Number(row.step),status:row.status as ArenaJourneyProgress["status"]} : null;
}
export function advanceArenaJourney(current: ArenaJourneyProgress, action: ArenaJourneyAction): ArenaJourneyProgress {
  if (action === "restart") return {step:0,status:"active"};
  if (current.status === "completed" || current.status === "skipped") return current;
  if (action === "skip") return {...current,status:"skipped"};
  if (action === "previous") return {step:Math.max(0,current.step-1),status:"active"};
  if (action === "next" && current.step === ARENA_JOURNEY_STEPS.length-1) return {...current,status:"completed"};
  return {step:Math.min(current.step+1,ARENA_JOURNEY_STEPS.length-1),status:"active"};
}
export function arenaJourneyStorageKey(userId: string) { return `arena-journey-v${ARENA_JOURNEY_VERSION}:${userId}`; }
