export type ArenaPlayableLessonId = "cards" | "equipment" | "culture" | "jury" | "market" | "collection" | "specialties" | "warehouse" | "missions" | "bank" | "investments" | "business" | "notebook";
export type ArenaLessonProgress = { instruction: string; complete: boolean };
export const ARENA_PLAYABLE_LESSONS: readonly { id: ArenaPlayableLessonId; title: string; description: string; image: string; group: "game" | "explore"; instruction: string }[] = [
  { id: "cards", title: "Préparer mes cartes", description: "Choisis ton Buddie, tes soutiens et ton Héritage dans la préparation du jeu.", image: "/app/lottery/sylvain-booster-presentation-v3.webp", group: "game", instruction: "Choisis ton Buddie puis prépare tes cartes sur les carrousels du jeu." },
  { id: "equipment", title: "Équiper mon placard", description: "Entre dans l’entrepôt, achète et installe du matériel.", image: "/placard/warehouse-v2/room.webp", group: "game", instruction: "Ouvre un emplacement dans l’entrepôt et installe ton matériel d’essai." },
  { id: "culture", title: "Jouer une culture", description: "Joue tes cartes, lance les vrais dés du jeu et récolte.", image: "/contest/mascot/arena-scene-placard-v1.png", group: "game", instruction: "Observe la situation, joue une préparation si tu le souhaites, puis lance les dés." },
  { id: "jury", title: "Présenter ma Fleur", description: "Entre dans le duel avec une Fleur prête et découvre le verdict.", image: "/contest/mascot/arena-scene-placard-v1.png", group: "game", instruction: "Présente ta Fleur prêtée au jury et lance le duel d’entraînement." },
  { id: "market", title: "Transformer et vendre", description: "Choisis un lot, transforme-le et confirme une vente au marché.", image: "/placard/channel-cbd-shop-v1.webp", group: "game", instruction: "Choisis une valorisation pour ton lot prêté, puis vends le produit obtenu." },
  { id: "collection", title: "Ouvrir un pack Buddies", description: "Ouvre un pack et révèle ses trois cartes avec les animations de ta collection.", image: "/app/lottery/sylvain-booster-presentation-v3.webp", group: "explore", instruction: "Ouvre le pack d’essai, retourne les trois cartes, puis range-les dans l’album fictif." },
  { id: "specialties", title: "Créer mon personnage", description: "Manipule l’éditeur d’apparence et essaie les spécialités.", image: "/contest/mascot/arena-lobby-sylvain-v1.png", group: "explore", instruction: "Donne un surnom à ton personnage d’essai, modifie son apparence puis choisis sa spécialité." },
  { id: "warehouse", title: "Entretenir et agrandir", description: "Améliore ton installation et retrouve l’entretien des machines.", image: "/placard/warehouse-v2/room.webp", group: "explore", instruction: "Ouvre la fiche d’un équipement pour le remettre en état ou améliorer ton installation." },
  { id: "missions", title: "Récupérer une récompense", description: "Récupère un défi accompli, puis ouvre son pack à la Boutique.", image: "/placard/booster-shop-counter-v5.webp", group: "explore", instruction: "Dans Tous mes défis, récupère le pack de ta première récolte puis ouvre-le à la Boutique." },
  { id: "bank", title: "Aller à la banque", description: "Manipule le livret et consulte un prêt avec un compte fictif.", image: "/placard/channel-online-v1.webp", group: "explore", instruction: "Entre au guichet et essaie un dépôt sur le livret du Trésorier." },
  { id: "investments", title: "Acheter et vendre une position", description: "Prépare un ordre sur les écrans Bourse et Crypto du jeu.", image: "/placard/channel-online-v1.webp", group: "explore", instruction: "Choisis un actif, vérifie ton ordre puis confirme un achat fictif." },
  { id: "business", title: "Gérer mon commerce", description: "Crée ton site et manipule sa gestion depuis le Bureau.", image: "/placard/channel-online-v1.webp", group: "explore", instruction: "Retrouve la gestion du site au Bureau et ouvre ton shop d’essai." },
  { id: "notebook", title: "Remplir mon Carnet", description: "Feuillette le vrai Carnet et remplis une fiche d’entraînement.", image: "/contest/mascot/arena-scene-carnet-v1.png", group: "explore", instruction: "Ouvre la Fleur d’essai et remplis ses pages. Ici, les notes sont fictives ; ton vrai Carnet décrit tes dégustations réelles." },
];
