export const KQ_CARD_ILLUSTRATIONS: Readonly<Record<string, string>> = {
  "BOTTE-001": "/app/kanab-quest/cards/botte-001-terreau-universel-v1.webp",
  "BOTTE-002": "/app/kanab-quest/cards/botte-002-chrysope-affamee-v1.webp",
  "BOTTE-003": "/app/kanab-quest/cards/botte-003-petit-ventilateur-v1.webp",
  "BOTTE-004": "/app/kanab-quest/cards/botte-004-loupe-inspection-v1.webp",
  "BOTTE-005": "/app/kanab-quest/cards/botte-005-arrosage-mesure-v1.webp",
  "BOTTE-006": "/app/kanab-quest/cards/botte-006-deuxieme-chance-v1.webp",
  "BOTTE-007": "/app/kanab-quest/cards/botte-007-fibre-coco-v1.webp",
  "BOTTE-008": "/app/kanab-quest/cards/botte-008-melange-drainant-v1.webp",
  "BOTTE-009": "/app/kanab-quest/cards/botte-009-terre-vivante-v1.webp",
  "BOTTE-010": "/app/kanab-quest/cards/botte-010-coccinelle-sept-points-v1.webp",
  "BOTTE-011": "/app/kanab-quest/cards/botte-011-amblyseius-swirskii-v1.webp",
  "BOTTE-012": "/app/kanab-quest/cards/botte-012-aphidius-colemani-v1.webp",
  "BOTTE-013": "/app/kanab-quest/cards/botte-013-pot-tissu-v1.webp",
  "BOTTE-014": "/app/kanab-quest/cards/botte-014-hygrometre-vintage-v1.webp",
  "BOTTE-015": "/app/kanab-quest/cards/botte-015-palissage-doux-v1.webp",
  "BOTTE-016": "/app/kanab-quest/cards/botte-016-sechage-patient-v1.webp",
  "BOTTE-017": "/app/kanab-quest/cards/botte-017-main-verte-v1.webp",
  "BOTTE-018": "/app/kanab-quest/cards/botte-018-coup-de-pouce-v1.webp",
  "BOTTE-019": "/app/kanab-quest/cards/botte-019-perlite-horticole-v1.webp",
  "BOTTE-020": "/app/kanab-quest/cards/botte-020-biochar-v1.webp",
  "BOTTE-021": "/app/kanab-quest/cards/botte-021-compost-mur-v1.webp",
  "BOTTE-022": "/app/kanab-quest/cards/botte-022-phytoseiulus-persimilis-v1.webp",
  "BOTTE-023": "/app/kanab-quest/cards/botte-023-orius-laevigatus-v1.webp",
  "BOTTE-024": "/app/kanab-quest/cards/botte-024-tensiometre-v1.webp",
  "BOTTE-025": "/app/kanab-quest/cards/botte-025-filet-anti-insectes-v1.webp",
  "BOTTE-026": "/app/kanab-quest/cards/botte-026-brasseur-air-v1.webp",
  "BOTTE-027": "/app/kanab-quest/cards/botte-027-timer-mecanique-v1.webp",
  "BOTTE-028": "/app/kanab-quest/cards/botte-028-taille-apicale-v1.webp",
  "BOTTE-029": "/app/kanab-quest/cards/botte-029-effeuillage-mesure-v1.webp",
  "BOTTE-030": "/app/kanab-quest/cards/botte-030-affinage-bocal-v1.webp",
  "BOTTE-031": "/app/kanab-quest/cards/botte-031-drainage-controle-v1.webp",
  "BOTTE-032": "/app/kanab-quest/cards/botte-032-carnet-jardinier-v1.webp",
  "BOTTE-033": "/app/kanab-quest/cards/botte-033-observation-matinale-v1.webp",
  "BOTTE-034": "/app/kanab-quest/cards/botte-034-retour-calme-v1.webp",
  "BOTTE-035": "/app/kanab-quest/cards/botte-035-quarantaine-preventive-v1.webp",
  "BOTTE-036": "/app/kanab-quest/cards/botte-036-bac-retention-v1.webp",
  "HERITAGE-001": "/app/kanab-quest/cards/heritage-001-racines-solides-v1.webp",
  "HERITAGE-002": "/app/kanab-quest/cards/heritage-002-reserve-jardinier-v1.webp",
  "HERITAGE-003": "/app/kanab-quest/cards/heritage-003-main-prevoyante-v1.webp",
  "HERITAGE-004": "/app/kanab-quest/cards/heritage-004-climat-stable-v1.webp",
  "HERITAGE-005": "/app/kanab-quest/cards/heritage-005-second-regard-v1.webp",
  "HERITAGE-006": "/app/kanab-quest/cards/heritage-006-reprise-vigoureuse-v1.webp",
  "HERITAGE-007": "/app/kanab-quest/cards/heritage-007-instinct-cultivateur-v1.webp",
  "HERITAGE-008": "/app/kanab-quest/cards/heritage-008-bouclier-biologique-v1.webp",
  "HERITAGE-009": "/app/kanab-quest/cards/heritage-009-floraison-maitrisee-v1.webp",
  "HERITAGE-010": "/app/kanab-quest/cards/heritage-010-affinage-patient-v1.webp",
  "HERITAGE-011": "/app/kanab-quest/cards/heritage-011-canopy-legacy-v1.webp",
  "HERITAGE-012": "/app/kanab-quest/cards/heritage-012-signature-maitre-v1.webp",
};

export const KQ_CARD_ARTWORK: Readonly<Record<string, string>> = Object.fromEntries(
  Object.entries(KQ_CARD_ILLUSTRATIONS).map(([code, source]) => [
    code,
    source.replace("/cards/", "/card-fronts/").replace("-v1.webp", "-front-v1.webp"),
  ]),
);

export function getKqCardArtwork(code: string) {
  return KQ_CARD_ARTWORK[code] ?? null;
}
