-- Generated by scripts/generate-placard-indoor-catalog.mjs.
-- Same definition IDs, ownership, rarity and pack odds. No card instance is removed.
BEGIN;
CREATE TEMP TABLE kq_indoor_deck_update ON COMMIT DROP AS
SELECT * FROM jsonb_to_recordset($deck$[
  {
    "code": "BOTTE-002",
    "name": "Chrysope affamée",
    "description": "Un dé faible (1, 2 ou 3) devient 4. Cible : pucerons ou thrips identifiés.",
    "image_url": "/app/kanab-quest/card-fronts/botte-002-chrysope-affamee-front-v5.webp",
    "category": "pbi",
    "timing": "after-roll",
    "effect": "pbi-success",
    "xp_cost": 2,
    "tags": [
      "pest"
    ],
    "targets": [
      "aphids",
      "thrips"
    ],
    "advantage": "Un dé faible (1, 2 ou 3) devient 4. Cible : pucerons ou thrips identifiés.",
    "drawback": "Ravageur identifié obligatoire. Ne sert pas contre les acariens."
  },
  {
    "code": "BOTTE-003",
    "name": "Petit ventilateur",
    "description": "Protège contre un Danger (1). Le dé ne devient pas une réussite.",
    "image_url": "/app/kanab-quest/card-fronts/botte-003-petit-ventilateur-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "cancel-danger",
    "xp_cost": 1,
    "tags": [
      "climate",
      "drying"
    ],
    "targets": [],
    "advantage": "Protège contre un Danger (1). Le dé ne devient pas une réussite.",
    "drawback": "Sans Danger au lancer, la protection est perdue."
  },
  {
    "code": "BOTTE-004",
    "name": "Loupe d’inspection",
    "description": "Identifie le ravageur, ouvre la réserve PBI et protège contre un Danger (1).",
    "image_url": "/app/kanab-quest/card-fronts/botte-004-loupe-inspection-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "reveal-pest",
    "xp_cost": 1,
    "tags": [
      "pest"
    ],
    "targets": [],
    "advantage": "Identifie le ravageur, ouvre la réserve PBI et protège contre un Danger (1).",
    "drawback": "Ne corrige aucun dé faible ; les PBI se jouent ensuite en réaction."
  },
  {
    "code": "BOTTE-005",
    "name": "Arrosage mesuré",
    "description": "Relance un dé neutre (2 ou 3). Le nouveau résultat est conservé.",
    "image_url": "/app/kanab-quest/card-fronts/botte-005-arrosage-mesure-front-v5.webp",
    "category": "know-how",
    "timing": "before-roll",
    "effect": "reroll-neutral",
    "xp_cost": 1,
    "tags": [
      "water",
      "roots"
    ],
    "targets": [],
    "advantage": "Relance un dé neutre (2 ou 3). Le nouveau résultat est conservé.",
    "drawback": "La relance peut donner un Danger (1)."
  },
  {
    "code": "BOTTE-006",
    "name": "Deuxième chance",
    "description": "Relance les deux dés les plus faibles. Les nouveaux résultats sont conservés.",
    "image_url": "/app/kanab-quest/card-fronts/botte-006-deuxieme-chance-front-v5.webp",
    "category": "luck",
    "timing": "after-roll",
    "effect": "reroll-two-low",
    "xp_cost": 2,
    "tags": [],
    "targets": [],
    "advantage": "Relance les deux dés les plus faibles. Les nouveaux résultats sont conservés.",
    "drawback": "Une bonne face peut aussi être relancée et devenir moins bonne."
  },
  {
    "code": "BOTTE-010",
    "name": "Coccinelle à sept points",
    "description": "Un dé faible devient 6 : une réussite et +1 XP au verdict. Cible : pucerons identifiés.",
    "image_url": "/app/kanab-quest/card-fronts/botte-010-coccinelle-sept-points-front-v5.webp",
    "category": "pbi",
    "timing": "after-roll",
    "effect": "pbi-strong-success",
    "xp_cost": 3,
    "tags": [
      "pest"
    ],
    "targets": [
      "aphids"
    ],
    "advantage": "Un dé faible devient 6 : une réussite et +1 XP au verdict. Cible : pucerons identifiés.",
    "drawback": "Coûte 3 XP et ne cible que les pucerons."
  },
  {
    "code": "BOTTE-011",
    "name": "Amblyseius swirskii",
    "description": "Un dé neutre (2 ou 3) devient 5. Cible : thrips identifiés.",
    "image_url": "/app/kanab-quest/card-fronts/botte-011-amblyseius-swirskii-front-v5.webp",
    "category": "pbi",
    "timing": "after-roll",
    "effect": "pbi-neutral-strong",
    "xp_cost": 1,
    "tags": [
      "pest"
    ],
    "targets": [
      "thrips"
    ],
    "advantage": "Un dé neutre (2 ou 3) devient 5. Cible : thrips identifiés.",
    "drawback": "Ne corrige pas les Dangers (1) et ne cible que les thrips."
  },
  {
    "code": "BOTTE-012",
    "name": "Aphidius colemani",
    "description": "Un dé faible devient 4. +1 XP si l’étape réussit. Cible : pucerons identifiés.",
    "image_url": "/app/kanab-quest/card-fronts/botte-012-aphidius-colemani-front-v5.webp",
    "category": "pbi",
    "timing": "after-roll",
    "effect": "pbi-success-xp",
    "xp_cost": 2,
    "tags": [
      "pest"
    ],
    "targets": [
      "aphids"
    ],
    "advantage": "Un dé faible devient 4. +1 XP si l’étape réussit. Cible : pucerons identifiés.",
    "drawback": "Le remboursement exige une réussite de l’étape."
  },
  {
    "code": "BOTTE-013",
    "name": "Voile d’ombrage",
    "description": "Un Danger (1) devient neutre (3). +1 Pression dès que la carte est jouée.",
    "image_url": "/app/kanab-quest/card-fronts/botte-013-voile-ombrage-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "shade-screen",
    "xp_cost": 1,
    "tags": [
      "light",
      "climate"
    ],
    "targets": [],
    "advantage": "Un Danger (1) devient neutre (3). +1 Pression dès que la carte est jouée.",
    "drawback": "Ajoute 1 Pression même si aucun Danger ne sort."
  },
  {
    "code": "BOTTE-014",
    "name": "Hygromètre vintage",
    "description": "−1 Pression immédiatement. Au lancer, un 3 devient 4.",
    "image_url": "/app/kanab-quest/card-fronts/botte-014-hygrometre-vintage-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "hygrometer-balance",
    "xp_cost": 2,
    "tags": [
      "water",
      "climate",
      "drying"
    ],
    "targets": [],
    "advantage": "−1 Pression immédiatement. Au lancer, un 3 devient 4.",
    "drawback": "Sans 3, aucun dé ne change ; la baisse de Pression reste acquise."
  },
  {
    "code": "BOTTE-015",
    "name": "Palissage doux",
    "description": "Au lancer, un dé neutre (2 ou 3) devient une réussite (4).",
    "image_url": "/app/kanab-quest/card-fronts/botte-015-palissage-doux-front-v5.webp",
    "category": "know-how",
    "timing": "before-roll",
    "effect": "neutral-to-success",
    "xp_cost": 2,
    "tags": [
      "flower"
    ],
    "targets": [],
    "advantage": "Au lancer, un dé neutre (2 ou 3) devient une réussite (4).",
    "drawback": "Sans dé neutre, aucun effet."
  },
  {
    "code": "BOTTE-016",
    "name": "Séchage patient",
    "description": "−1 Pression immédiatement. +1 Qualité si l’étape réussit.",
    "image_url": "/app/kanab-quest/card-fronts/botte-016-sechage-patient-front-v5.webp",
    "category": "know-how",
    "timing": "before-roll",
    "effect": "patient-curing",
    "xp_cost": 2,
    "tags": [
      "drying"
    ],
    "targets": [],
    "advantage": "−1 Pression immédiatement. +1 Qualité si l’étape réussit.",
    "drawback": "Ne corrige pas les dés ; le bonus Qualité exige une réussite."
  },
  {
    "code": "BOTTE-017",
    "name": "Main verte",
    "description": "Lance 4 dés et garde les 3 meilleurs.",
    "image_url": "/app/kanab-quest/card-fronts/botte-017-main-verte-front-v5.webp",
    "category": "luck",
    "timing": "before-roll",
    "effect": "four-keep-three",
    "xp_cost": 2,
    "tags": [],
    "targets": [],
    "advantage": "Lance 4 dés et garde les 3 meilleurs.",
    "drawback": "Coûte 2 XP sans garantir la réussite."
  },
  {
    "code": "BOTTE-018",
    "name": "Thermomètre infrarouge",
    "description": "Relance le dé le plus faible. Récupère 1 XP si sa valeur augmente.",
    "image_url": "/app/kanab-quest/card-fronts/botte-018-thermometre-infrarouge-front-v5.webp",
    "category": "equipment",
    "timing": "after-roll",
    "effect": "thermal-check",
    "xp_cost": 2,
    "tags": [
      "climate",
      "light"
    ],
    "targets": [],
    "advantage": "Relance le dé le plus faible. Récupère 1 XP si sa valeur augmente.",
    "drawback": "La relance peut être moins bonne. Aucun remboursement en cas d’égalité."
  },
  {
    "code": "BOTTE-019",
    "name": "Minuteur recalé",
    "description": "Corrige un seul dé : un 1 devient 2 ; sans 1, un 2 devient 4.",
    "image_url": "/app/kanab-quest/card-fronts/botte-019-minuteur-recale-front-v5.webp",
    "category": "equipment",
    "timing": "after-roll",
    "effect": "timer-reset",
    "xp_cost": 1,
    "tags": [
      "light",
      "energy"
    ],
    "targets": [],
    "advantage": "Corrige un seul dé : un 1 devient 2 ; sans 1, un 2 devient 4.",
    "drawback": "Ne corrige pas les 3. Un Danger devient seulement neutre."
  },
  {
    "code": "BOTTE-020",
    "name": "Nettoyage du placard",
    "description": "Au lancer, un 1 devient 3 et retire 1 Pression. Sans 1, aucun effet.",
    "image_url": "/app/kanab-quest/card-fronts/botte-020-nettoyage-placard-front-v5.webp",
    "category": "know-how",
    "timing": "before-roll",
    "effect": "hygiene-buffer",
    "xp_cost": 2,
    "tags": [
      "pest",
      "hygiene"
    ],
    "targets": [],
    "advantage": "Au lancer, un 1 devient 3 et retire 1 Pression. Sans 1, aucun effet.",
    "drawback": "Coûte 2 XP ; sans Danger, aucune baisse de Pression."
  },
  {
    "code": "BOTTE-021",
    "name": "Diagnostic croisé",
    "description": "Avec exactement 2 réussites, le dernier dé neutre devient 6 : réussite critique et +1 XP au verdict.",
    "image_url": "/app/kanab-quest/card-fronts/botte-021-diagnostic-croise-front-v5.webp",
    "category": "know-how",
    "timing": "after-roll",
    "effect": "cross-diagnosis",
    "xp_cost": 2,
    "tags": [],
    "targets": [],
    "advantage": "Avec exactement 2 réussites, le dernier dé neutre devient 6 : réussite critique et +1 XP au verdict.",
    "drawback": "Exige 2 réussites et un 2 ou un 3. Impossible de sauver un mauvais lancer."
  },
  {
    "code": "BOTTE-022",
    "name": "Phytoseiulus persimilis",
    "description": "Un Danger (1) devient 4. Protège contre un autre Danger. Cible : acariens identifiés.",
    "image_url": "/app/kanab-quest/card-fronts/botte-022-phytoseiulus-persimilis-front-v5.webp",
    "category": "pbi",
    "timing": "after-roll",
    "effect": "pbi-mite-shield",
    "xp_cost": 3,
    "tags": [
      "pest"
    ],
    "targets": [
      "mites"
    ],
    "advantage": "Un Danger (1) devient 4. Protège contre un autre Danger. Cible : acariens identifiés.",
    "drawback": "Exige un Danger et des acariens identifiés. Coûte 3 XP."
  },
  {
    "code": "BOTTE-023",
    "name": "Orius laevigatus",
    "description": "Un dé faible devient 4 et retire 1 Pression. Cible : thrips identifiés.",
    "image_url": "/app/kanab-quest/card-fronts/botte-023-orius-laevigatus-front-v5.webp",
    "category": "pbi",
    "timing": "after-roll",
    "effect": "pbi-thrips-relief",
    "xp_cost": 2,
    "tags": [
      "pest"
    ],
    "targets": [
      "thrips"
    ],
    "advantage": "Un dé faible devient 4 et retire 1 Pression. Cible : thrips identifiés.",
    "drawback": "Ne cible que les thrips identifiés."
  },
  {
    "code": "BOTTE-024",
    "name": "Réserve d’eau de secours",
    "description": "Un Danger (1) devient une réussite (4). Ajoute 1 Pression.",
    "image_url": "/app/kanab-quest/card-fronts/botte-024-reserve-eau-secours-front-v5.webp",
    "category": "equipment",
    "timing": "after-roll",
    "effect": "water-rescue",
    "xp_cost": 1,
    "tags": [
      "water"
    ],
    "targets": [],
    "advantage": "Un Danger (1) devient une réussite (4). Ajoute 1 Pression.",
    "drawback": "Ajoute 1 Pression ; à 3 Pression, le seuil de réussite augmente."
  },
  {
    "code": "BOTTE-025",
    "name": "Plaque engluée de suivi",
    "description": "Identifie le ravageur, ouvre la réserve PBI et rembourse son coût de 1 XP.",
    "image_url": "/app/kanab-quest/card-fronts/botte-025-plaque-engluee-suivi-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "pest-monitor",
    "xp_cost": 1,
    "tags": [
      "pest"
    ],
    "targets": [],
    "advantage": "Identifie le ravageur, ouvre la réserve PBI et rembourse son coût de 1 XP.",
    "drawback": "Exige 1 XP disponible. Aucun dé corrigé ni Danger protégé."
  },
  {
    "code": "BOTTE-026",
    "name": "Extracteur bien réglé",
    "description": "Protège contre 2 Dangers (1). Les dés ne deviennent pas des réussites.",
    "image_url": "/app/kanab-quest/card-fronts/botte-026-extracteur-bien-regle-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "double-danger-shield",
    "xp_cost": 2,
    "tags": [
      "climate",
      "drying"
    ],
    "targets": [],
    "advantage": "Protège contre 2 Dangers (1). Les dés ne deviennent pas des réussites.",
    "drawback": "Coûte 2 XP, même avec zéro ou un seul Danger."
  },
  {
    "code": "BOTTE-027",
    "name": "Papiers en règle",
    "description": "Les 3 dés deviennent 4 : réussite critique garantie au contrôle DDTM.",
    "image_url": "/app/kanab-quest/card-fronts/botte-027-papiers-en-regle-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "compliance-clearance",
    "xp_cost": 3,
    "tags": [
      "compliance"
    ],
    "targets": [],
    "advantage": "Les 3 dés deviennent 4 : réussite critique garantie au contrôle DDTM.",
    "drawback": "Coûte 3 XP et ne sert qu’au contrôle DDTM."
  },
  {
    "code": "BOTTE-028",
    "name": "Branchement illégal",
    "description": "Sur une surcharge non maîtrisée, les 2 dés les plus faibles deviennent 4. +2 Pression.",
    "image_url": "/app/kanab-quest/card-fronts/botte-028-branchement-illegal-front-v5.webp",
    "category": "luck",
    "timing": "after-roll",
    "effect": "illegal-power",
    "xp_cost": 1,
    "tags": [
      "energy"
    ],
    "targets": [],
    "advantage": "Sur une surcharge non maîtrisée, les 2 dés les plus faibles deviennent 4. +2 Pression.",
    "drawback": "Ajoute 2 Pression : la réussite reste soumise au nouveau seuil."
  },
  {
    "code": "BOTTE-029",
    "name": "Effeuillage mesuré",
    "description": "Relance un dé neutre (2 ou 3) en gardant la meilleure valeur. +1 Pression immédiate.",
    "image_url": "/app/kanab-quest/card-fronts/botte-029-effeuillage-mesure-front-v5.webp",
    "category": "know-how",
    "timing": "before-roll",
    "effect": "leaf-thinning",
    "xp_cost": 1,
    "tags": [
      "flower",
      "climate"
    ],
    "targets": [],
    "advantage": "Relance un dé neutre (2 ou 3) en gardant la meilleure valeur. +1 Pression immédiate.",
    "drawback": "Ajoute 1 Pression même sans dé neutre."
  },
  {
    "code": "BOTTE-030",
    "name": "Sonde d’humidité",
    "description": "Un 3 devient 5 ; sans 3, un 2 devient 4. Une seule correction.",
    "image_url": "/app/kanab-quest/card-fronts/botte-030-sonde-humidite-front-v5.webp",
    "category": "equipment",
    "timing": "after-roll",
    "effect": "moisture-calibration",
    "xp_cost": 2,
    "tags": [
      "drying"
    ],
    "targets": [],
    "advantage": "Un 3 devient 5 ; sans 3, un 2 devient 4. Une seule correction.",
    "drawback": "Exige un dé neutre au Séchage. Ne corrige pas les Dangers."
  },
  {
    "code": "BOTTE-031",
    "name": "Échéancier négocié",
    "description": "Réduit de 1 le nombre de réussites demandé, avec un minimum de 1.",
    "image_url": "/app/kanab-quest/card-fronts/botte-031-echeancier-negocie-front-v5.webp",
    "category": "know-how",
    "timing": "before-roll",
    "effect": "bill-relief",
    "xp_cost": 1,
    "tags": [
      "energy"
    ],
    "targets": [],
    "advantage": "Réduit de 1 le nombre de réussites demandé, avec un minimum de 1.",
    "drawback": "Ne retire pas les Dangers et ne sert qu’en Énergie."
  },
  {
    "code": "BOTTE-032",
    "name": "Loupe à trichomes",
    "description": "Lance 4 dés, garde les 3 meilleurs. +1 Qualité si l’étape réussit.",
    "image_url": "/app/kanab-quest/card-fronts/botte-032-loupe-trichomes-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "harvest-four-quality",
    "xp_cost": 2,
    "tags": [
      "harvest"
    ],
    "targets": [],
    "advantage": "Lance 4 dés, garde les 3 meilleurs. +1 Qualité si l’étape réussit.",
    "drawback": "Réservée à la Récolte. Le bonus Qualité exige une réussite."
  },
  {
    "code": "BOTTE-033",
    "name": "Récolte au frais",
    "description": "Protège contre un Danger (1). −1 Pression si cette protection sert.",
    "image_url": "/app/kanab-quest/card-fronts/botte-033-recolte-frais-front-v5.webp",
    "category": "know-how",
    "timing": "before-roll",
    "effect": "harvest-cool",
    "xp_cost": 1,
    "tags": [
      "harvest",
      "climate"
    ],
    "targets": [],
    "advantage": "Protège contre un Danger (1). −1 Pression si cette protection sert.",
    "drawback": "Sans Danger protégé, aucune baisse de Pression."
  },
  {
    "code": "BOTTE-034",
    "name": "Gros molosse",
    "description": "Aucune perte de récolte lors du vol, même si les dés échouent.",
    "image_url": "/app/kanab-quest/card-fronts/botte-034-gros-molosse-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "theft-guard",
    "xp_cost": 2,
    "tags": [
      "security"
    ],
    "targets": [],
    "advantage": "Aucune perte de récolte lors du vol, même si les dés échouent.",
    "drawback": "Ne change ni les dés ni la qualité obtenue à cette étape."
  },
  {
    "code": "BOTTE-035",
    "name": "Récolte par lots",
    "description": "Un Danger (1) devient neutre (3). Sauve un jet risqué sans relance.",
    "image_url": "/app/kanab-quest/card-fronts/botte-035-recolte-lots-front-v5.webp",
    "category": "know-how",
    "timing": "after-roll",
    "effect": "danger-to-neutral",
    "xp_cost": 2,
    "tags": [
      "harvest",
      "drying",
      "hygiene"
    ],
    "targets": [],
    "advantage": "Un Danger (1) devient neutre (3). Sauve un jet risqué sans relance.",
    "drawback": "Coûte 2 XP et ne crée aucune réussite."
  },
  {
    "code": "BOTTE-036",
    "name": "Sécateur propre",
    "description": "Protège contre un Danger (1). +1 XP si l’étape réussit.",
    "image_url": "/app/kanab-quest/card-fronts/botte-036-secateur-propre-front-v5.webp",
    "category": "equipment",
    "timing": "before-roll",
    "effect": "clean-cut",
    "xp_cost": 1,
    "tags": [
      "harvest",
      "hygiene"
    ],
    "targets": [],
    "advantage": "Protège contre un Danger (1). +1 XP si l’étape réussit.",
    "drawback": "Le remboursement exige une réussite de l’étape."
  }
]$deck$::jsonb)
AS card(code text, name text, description text, image_url text, category text, timing text,
  effect text, xp_cost smallint, tags text[], targets text[], advantage text, drawback text);

DO $$ BEGIN
  IF (SELECT count(*) FROM public.lottery_card_definitions d JOIN kq_indoor_deck_update u USING (code)) <> 32
    OR (SELECT count(*) FROM public.kq_support_card_rules r JOIN public.lottery_card_definitions d ON d.id = r.card_definition_id JOIN kq_indoor_deck_update u USING (code)) <> 32 THEN
    RAISE EXCEPTION 'indoor_deck_catalog_incomplete';
  END IF;
END $$;

ALTER TABLE public.kq_support_card_rules DROP CONSTRAINT IF EXISTS kq_support_card_rules_effect_check;
ALTER TABLE public.kq_support_card_rules ADD CONSTRAINT kq_support_card_rules_effect_check
CHECK (effect IN ('aeroponic-precision', 'bill-relief', 'biochar-buffer', 'cancel-danger', 'clean-cut', 'compliance-clearance', 'compost-buffer', 'cross-diagnosis', 'danger-to-neutral', 'double-danger-shield', 'four-keep-three', 'harvest-cool', 'harvest-four-quality', 'hydroponic-control', 'hygiene-buffer', 'hygrometer-balance', 'illegal-power', 'leaf-thinning', 'living-soil-buffer', 'moisture-calibration', 'neutral-to-success', 'organic-feed', 'patient-curing', 'pbi-mite-shield', 'pbi-neutral-strong', 'pbi-strong-success', 'pbi-success', 'pbi-success-xp', 'pbi-thrips-relief', 'perlite-drainage', 'pest-monitor', 'reroll-neutral', 'reroll-two-low', 'reveal-pest', 'root-aeration', 'safe-neutral-reroll', 'shade-screen', 'starter-stability', 'theft-guard', 'thermal-check', 'three-to-success', 'timer-reset', 'water-rescue', 'water-test'));

UPDATE public.lottery_card_definitions d
SET name = u.name, description = u.description, image_url = u.image_url, updated_at = now()
FROM kq_indoor_deck_update u WHERE d.code = u.code;

UPDATE public.kq_support_card_rules r
SET category = u.category, timing = u.timing, effect = u.effect, xp_cost = u.xp_cost,
  tags = u.tags, targets = u.targets, advantage = u.advantage, drawback = u.drawback,
  rules_version = r.rules_version + 1, updated_at = now()
FROM kq_indoor_deck_update u JOIN public.lottery_card_definitions d USING (code)
WHERE r.card_definition_id = d.id;
COMMIT;
